### ISSUE TITLE
Users should be able to store/retrieve app related preferences

### ISSUE THREAD

**Issue by idormenco** [commitglobal/votemonitor#111]
* Vote.Monitor.Api.Feature.Preferences 
  - [ ] Add update endpoint POST /api/preferences 
  - [ ] Add get endpoint GET /api/preferences
* Preferences should be stored as [JSON column](https://www.npgsql.org/efcore/mapping/json.html#tojson-owned-entity-mapping) in User entity 
* Store languageId (guid) in preferences
* Unit & integration tests

**Comment by cosminbuda** [comment]
i can take this PR

**Comment by andreiio** [comment]
All yours!

**Comment by cosminbuda** [comment]
Q:  Should be language a mandatory item?

**Comment by cosminbuda** [comment]
Since I received no response, I will implement preferences as a list of key-value pairs. On update, I will enforce the language ID.
