### ISSUE TITLE
5.5.5 Media Management

### ISSUE THREAD

**Issue by andrei-manda** [commitglobal/votemonitor#167]
## User Story
As a user, I want to be able to add notes or media files at each step through Form Completion Wizard, so that I can provide relevant information as needed.

## Description

In the Form Completion Wizard, users should have the ability to attach notes, photos, videos or audio at each step of the process. Additionally, users should have the option to remove any attachments they've added.

## Preconditions

* The user is completing the Form Completion Wizard.
* [**Alt. Flow 1** / **Alt. Flow 2**] The question must have a note added.
* [**Alt. Flow 3**] The question must have one media added.

## Main Flow 1 (add note)

1. User selects the "Add Note or Media" option.
2. The system prompts the user with a bottom sheet offering the following choices:
                   - add note
                   - load from gallery
                   - take a photo
                   - record a video
                   - upload audio
3. User chooses the "Add note" option.
4. The system displays a modal for entering notes.
5. User enters their notes and clicks on the "Save" button.
6. The system saves the notes and presents them in a new section below the answer section.

## Main Flow 2 (add photo)
1. User selects the "Add Note or Media" option.
2. The system presents a bottom sheet with various options.
3. User selects the "Load from gallery" option.
4. The system opens the native photo gallery of the operating system. 
5. User chooses the desired photo from the gallery.
6. The system saves the selected photo and adds it to the "Uploaded Media" section.

## Alternative Flow 1 (edit note)

1. User selects the edit icon for the note.
2. The system presents the "Edit Note" modal for the user.
3. User makes edits to the note and clicks the "Save" button.
4. The system updates the note with the user's changes accordingly.

## Alternative Flow 2 (delete note)

1. User selects the edit icon for the note.
2. The system presents the "Edit Note" modal for the user.
3. User clicks on "Delete note" button.
4. The system prompts the user with a confirmation modal.
5. User confirms the deletion by clicking on the "Delete" button.
6. The system proceeds to delete the note as requested by the user.

## Alternative Flow 3 (delete media)
1. User selects an uploaded media item and clicks on the "X" mark icon.
2. The system prompts the user with a confirmation modal.
3. User confirms the deletion by clicking on the "Delete" button.
4. The system proceeds to delete the media file as requested by the user.

## Business Rules

1. The Form Completion Wizard must provide users with the capability to add, edit, or remove notes or media files for every question presented within the wizard.
2. The "Load from gallery" option should open the native gallery app on the device.
3. The "Take a photo" option must open the native camera app in photo mode.
4. The "Record a video" option must open the native camera app in video mode.
5. The "Upload Audio" option must open the native file system with filters set on audio files.

## Acceptance Criteria

1. The system must allow users to add, edit, or remove notes or media files at each step of the Form Completion Wizard.
2. Users can select an uploaded media item and click the "X" icon to initiate deletion.
3. The "Load from gallery" option should include support multi-selection to add multiple media files at once.

## Additional Information

* Figma references [here](https://www.figma.com/file/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?type=design&node-id=1197-1914&mode=design&t=CfHNqKdw3xUJrBPM-4)

**Comment by radulescuandrew** [comment]
@andrei-manda Please include "Upload audio file" as was requested later and implemented.
