### ISSUE TITLE
[NGO Admin] Missing Back/Next buttons in form bulder preview box

### ISSUE THREAD

**Issue by overeha** [commitglobal/votemonitor#409]
Summary: 
The preview area lacks the back and forth buttons for navigating through the questions without clicking each time on the question card.  

Expected behavior:
[Check Figma file for the preview box design here.](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=2636-13619&t=bGM8y2L5nn21wEmz-4). 

System: 
Windows

**Comment by vladplesu** [comment]
I can take this one

**Comment by idormenco** [comment]
@vladplesu this issue was fixe by @bogdani189

**Comment by idormenco** [comment]
this was fixed
