### ISSUE TITLE
[NGO Admin] [Form builder] Wrong color of add question card

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#419]
Summary:
On the "Add Question" card from the form builder, the left area where is the plus icon should be purple as in [Figma](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=2586-19177&t=PC6NOC9A3ejgVT1V-4),  instead of black (to suggest that is clickable).

**Comment by idormenco** [comment]
fixed in #477
