### ISSUE TITLE
[NGO Admin] [Monitoring Observers] Filtering observers by tags is working as reunion not as intersection

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#421]
**Summary**:
Filtering observers by tags is working as reunion not intersection. If I filter observers by several tags, all returned results contain at least one of the tags. To be a useful feature for the NGO, **the filter should return only the results that match all the selected filters/tags**.  The goal is to reduce the results (especially when sending push notifications only to a subgroup of observers).

**Steps to Reproduce:**

1. Import a list of observers with tags
2. Filter by several tags
3. See that as you add more filters, the results are not reduced

**Expected result:**
The filters should work as intersections. 
![B6](https://github.com/commitglobal/votemonitor/assets/137993344/de30bb9b-c4d4-4485-a2a7-c91f70eb0c58)

**Comment by idormenco** [comment]
on it

**Comment by avasi-code4ro** [comment]
I reopened this issue because of our yesterday's discussion. 

The conclusion is that both in the monitoring observers list page and in the create push message, **filtering inside tags will work as intersection**, but between tags and other criteria, such as (observer status or polling stations levels/location), **filtering will work as reunion.** @idormenco
