### ISSUE TITLE
[NGO Admin] [Monitoring Observers] Missing empty state page when you don't have a list of observers imported yet

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#425]
[Here ](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=909-30381&t=bGM8y2L5nn21wEmz-4) link from the missing page.

**Comment by vladplesu** [comment]
I can take this
