### ISSUE TITLE
[NGO Admin] [General] The navigation is different from Figma

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#428]
Summary:
The navigation is different from [Figma](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=909-19633&t=PN1zo1oe8EIGmM2C-4). It should be Dashboard, Election event, Observers, Responses. The forms should be under the Election event.

**Comment by idormenco** [comment]
forms will be moved under the Election event when we will finish with formbuilder
