### ISSUE TITLE
[NGO Admin] [Monitoring Observers] Observers tags are oddly truncated in the observers list table

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#431]
Summary:
Tags are truncated in a non user friendly manner (you can not see the text of the truncated tag in the table). We should permit the tags overflow on two rows and only then truncated if there are more tags. 

![image (1)](https://github.com/commitglobal/votemonitor/assets/137993344/e360c66f-41b1-4a49-bc33-8fbaeb97dba0)

**Comment by avasi-code4ro** [comment]
It is still a problem here, the content in the "Observer Tags" column overlaps with the "Email" column. This issue is likely due to the columns being set to a fixed width. Also, cell content, including tags, should be allowed to overflow onto two rows. If the content exceeds this limit, it should be truncated and followed by an ellipsis, as I suggested above.
![Screenshot 2024-05-30 at 16 48 33](https://github.com/commitglobal/votemonitor/assets/137993344/534e908d-471b-4f5f-a1e9-4d505ee3ee68)

Expected Behavior:

- Cell content should overflow onto two rows if needed.
- If content exceeds two rows, it should be truncated and followed by an ellipsis.
- Also, maybe allowing columns to have a flexible width would help in this case.

**Comment by imdeaconu** [comment]
I think I solved this. I also added a tooltip on hover for all columns using the title attribute so this should also solve a part of #603. PR incoming.
