### ISSUE TITLE
[NGO Admin] [Forms] We should permit creating a form that has "other" type 

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#434]
In our research it was raised the need of creating other types of forms, besides the three standard ones (ex. for the evaluation of accessibility measures in polling stations or other niche topic.) We should add an "other" option in the form type dropdown as illustrated in [Figma](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=5192-16604&t=PN1zo1oe8EIGmM2C-4).

![image (2)](https://github.com/commitglobal/votemonitor/assets/137993344/ac9d5ec8-50c8-44dc-b2d9-05ea6266d1b0)

**Comment by idormenco** [comment]
on it
