### ISSUE TITLE
[NGO Admin] [Form builder] When edit a form, the name of the page and the back button are missing

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#436]
Summary: When edit a form, the name of the page and the back button are missing

Steps to Reproduce:

1. Go on the Forms page
2. Open a form 
3. Edit a form 
4. See that edit form page doesn't have back button + the name of the page. 

Back button should redirect to view page.
![image (4)](https://github.com/commitglobal/votemonitor/assets/137993344/b8166d04-01ca-4356-b6fa-37a7b7dd37c8)
![image (5)](https://github.com/commitglobal/votemonitor/assets/137993344/f06d8b1b-a3f0-4773-bffa-4e42c1c33fa4)

**Comment by idormenco** [comment]
resolved in #408
