### ISSUE TITLE
[NGO Admin] [Form builder] Display logic toggle should be disabled for a question that doesn't have previous questions

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#440]
Summary: 
When you switch on the display logic toggle for the first question in the form, there are no previous question to select from. 

We propose that in this case, when there are no other questions above, the display logic toggle to be disabled (the user will not be able to switch on), but when hovering on the toggle, to be displayed the next message "You need to have at least one prior question to connect the display logic to".

**Comment by idormenco** [comment]
on it

**Comment by idormenco** [comment]
@avasi-code4ro correct message should be "You need to have a prior question of type number question/rating question/single select / multiple select to enable display logic". You can have 10 text questions before current one and not be able to have display logic.

**Comment by idormenco** [comment]
closed in #508
