### ISSUE TITLE
[NGO Admin] [Form builder] Some input fields from the question card need relabeling for more clarity 

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#441]
- Instead of "code", to be "Question number/ ID"
- Instead of "Text", to be " Question content or text"
- Instead of "Help text", to be "Supplementary details (helptext) displayed under question"

![image (8)](https://github.com/commitglobal/votemonitor/assets/137993344/a9fefea9-3bac-45df-89e9-3828a6dd770b)

**Comment by idormenco** [comment]
@bogdani189 can you handle this please
