### ISSUE TITLE
[NGO Admin] [Monitoring observers] When editing an observer, if click on "cancel", the system respond with an inaccurate toast message

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#447]
**Summary:** 
Click on cancel when editing an observer display a wrong toast message (the one in the screenshot). 

Cancel button should redirect the user to the list of observers, without any toast message.

![image (12)](https://github.com/commitglobal/votemonitor/assets/137993344/38ffcc65-8dfc-4b6a-83fd-4993ee177299)

**Comment by idormenco** [comment]
on it
