### ISSUE TITLE
[NGO Admin] [Monitoring Observers] Creating a new push message page is crowded, as there is no spacing between elements

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#460]
Summary:
Creating a new push message page is crowded, as there is no spacing between elements. For a better user experience, I propose adding a sub header/ subtitle for each step, to create a better visual hierarchy. [Here is the proposal. ](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=5306-17093&t=lYstImixLdnpfjlI-4)

Also, would be helpful for the ONG Admins to see by **default at least 25 observers** in the list, to see better how the results are reduced. 
![Screenshot 2024-05-23 at 14 38 15](https://github.com/commitglobal/votemonitor/assets/137993344/1e5c10ae-30fb-467e-b283-e419d1a66ca8)

**Comment by vladplesu** [comment]
I can take it
