### ISSUE TITLE
[NGO Admin] [Responses] Filter or view reset on back button in responses section

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#471]
Summary:
When a user applies a filter or view (ex. apply view list by responses) and then enters a record to view its details, clicking the back button resets the list to the default view (view by entry) instead of retaining the applied filter/view. The expected behavior is for the applied filter/view to persist until the user navigates to a different section. This issue affects the usability of the responses section, as users have to reapply their preferred filter/view every time they return to the list, which can be time-consuming and frustrating.

Steps to Reproduce:

1. Go to responses section
2. Apply some tags or set view by responses/ or by observer
3. Click on a form to view its details.
4. Click the back button to return to the list.

Actual Result:
The list resets to the default view, sorted by entry.

Expected Result:
The list should retain the applied filter/view (sorted by responses) until the user navigates to a different section.

**Comment by vladplesu** [comment]
I can take it
