### ISSUE TITLE
[NGO Admin] [Monitoring observers]  Filter reset on back button in monitoring observers list

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#472]
When an user applies multiple filters to the observer list (ex. by tags) and then views the details of an observer, clicking the back button resets the list, eliminating all applied filters. The expected behaviour is for the applied filters to persist until the user navigates to a different section.

Steps to Reproduce:

1. Navigate to the monitoring observers list.
2. Apply multiple filters to the list (apply some tags)
3. Click on an observer to view his details.
4. Click the back button to return to the observer list.

Actual Result:
The observer list resets, removing all applied filters.

Expected Result:
The observer list should retain the applied filters until the user navigates to a different section.

**Comment by imdeaconu** [comment]
I have an idea on how to fix this: I'm thinking about using `URLSearchParams `as  a single source of truth for the filtering UI and the fetch requests, similarly to how pagination is currently handled. Maybe a custom hook that wraps URLSearchParams and could behave in the same way regardless of where it's used in the app could be a good addition.

**Comment by imdeaconu** [comment]
Can I have this assigned to me please? Thank you!

**Comment by idormenco** [comment]
all yours @imdeaconu
