### ISSUE TITLE
[NGO Admin][Responses] Relabeling needed for "Tags" from the table columns in view by entry

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#475]
Summary:
Relabeling needed for "Tags" from the table columns in view by entry. As these "Tags" refers to the column from the polling station list, I would suggest renaming in **"Station tags"** to avoid confusion with "Observers tags"

<img width="243" alt="Screenshot 2024-05-24 at 14 32 13" src="https://github.com/commitglobal/votemonitor/assets/137993344/24b613e4-26ec-42b0-9d1a-510b55be3265">

To be changed also in the polling station list. 
<img width="1419" alt="Screenshot 2024-05-24 at 14 33 44" src="https://github.com/commitglobal/votemonitor/assets/137993344/d5a65065-595b-4370-b789-4ef4f7748de2">

**Comment by idormenco** [comment]
closed in #488
