### ISSUE TITLE
[Observers] Observers accepting invites aren't taken away from page

### ISSUE THREAD

**Issue by tudoramariei** [commitglobal/votemonitor#478]
## Steps to Reproduce:

1. The Observer receives an invitation link
2. Open the invite link in a new tab, not logged in
3. Fill in the new password and click "Accept Invite"
4. The green notification appears **and the user stays on the page**
5. Trying to Accept invite again leads to an error
6. The user is never redirected from this page, even after a refresh

## Screenshots

<img width="976" alt="Screenshot 2024-05-25 at 12 11 16" src="https://github.com/commitglobal/votemonitor/assets/2820084/e3d223a1-45ae-4728-9d1c-50caea684743">

**Comment by idormenco** [comment]
@avasi-code4ro we need a design for this
