### ISSUE TITLE
[Observers] Different minimum password length requirements

### ISSUE THREAD

**Issue by danniel** [commitglobal/votemonitor#486]
Steps to Reproduce:

1. Using the web browser, follow an NGO Admin invitation link
2. When asked to set up your password for the new account, enter the password `123`
3. An error will appear informing you that the minimum password length is 6 chars
4. Enter the password `123456` and everything will work fine
5. Login to the mobile app
6. Go to `More` > `Change password`
7. You cannot set a password shorter than 8 chars

**Comment by avasi-code4ro** [comment]
@idormenco said that it's fixed now
