### ISSUE TITLE
[Observers][Set up the account & forgot password] Screens added in Figma for both of the cases

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#498]
Account confirmation - success message [here](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=5581-16938&t=PdfMsZIjPGIUR7dt-4).

Password reset after click on forgot password -  success message [here](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=5585-16968&t=PdfMsZIjPGIUR7dt-4).  
(Back to app button should open the VM app, if the user is on mobile when configuring his new password)

**Comment by vladplesu** [comment]
I can take this
