### ISSUE TITLE
[NGO Admin] [Observer forms] When edit a translation for a form, the drag option of the questions should be disabled as well 

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#501]
When edit a translation for a form, the **drag option** of the questions should be disabled as well, to not change the order of the questions by mistake (because it will be hard to keep track of translation progress)

Besides this I would decrease the opacity of display logic toggle & of the utility icons, or I would remove them. Despite the fact that the behaviour is correct (the user can not delete, reorder, add logic etc. to a question in a trasnlation form), being visible could distract the user and invite him indirectly to click on those buttons. So either I would decrease their opacity, either I would remove them. 

![Screenshot 2024-05-27 at 17 16 30](https://github.com/commitglobal/votemonitor/assets/137993344/62c15d7b-87e5-42e6-bc6a-fd7491ace2eb)

**Comment by vladplesu** [comment]
I can take this
