### ISSUE TITLE
[NGO Admin] [Observer forms] Save and exit doesn't do exit on edit form translation

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#502]
Summary: 
When editing a form translation, If I click on save and exit form editor, I still remain on the form editor. 

Expected result:
1. The user should be informed that he can't publish the form in the future if there are missing translations in the selected language. T[his message should be displayed](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=2593-33650&t=PdfMsZIjPGIUR7dt-4), along with the list of untranslated questions, by their code (we can implement this for the future if it is too hard now).

2. The user will either go back to the form editor, or will save the progress anyway and exit the form. In the second case, the user will be redirected to the list of forms.

**Comment by vladplesu** [comment]
I can take this
