### ISSUE TITLE
Write Unit Tests for Vote.Monitor.Api.Feature.CSOAdmin

### ISSUE THREAD

**Issue by idormenco** [commitglobal/votemonitor#51]
Write unit tests similar to those found in `Vote.Monitor.Api.Feature.PollingStation.UnitTests`

**Comment by lidiaMicusan** [comment]
I'm on it

**Comment by idormenco** [comment]
all yours @lidiaMicusan

**Comment by idormenco** [comment]
Hi @lidiaMicusan any updates on this issue ?

**Comment by lidiaMicusan** [comment]
Hi @idormenco
No. I didn't get to it
