### ISSUE TITLE
[NGO Admin] [Form builder] Pre-filled Input Fields Require Manual Deletion

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#516]
Users are required to manually delete the pre-filled text inside input fields before entering their information. This can be frustrating and time-consuming, especially when there are multiple forms or questions to answer to enter in the system.

Steps to Reproduce:

1. Navigate to the form builder.
2. Add a question and observe input fields that are pre-filled with text.
3. Attempt to enter information in the input fields.
3. Notice that the pre-filled text must be manually deleted before entering new information.

Expected behaviour:
Automatically clear when the user begins to type, or use placeholder text that disappears when the user clicks into the field.

![Screenshot 2024-05-29 at 12 58 22](https://github.com/commitglobal/votemonitor/assets/137993344/995b157f-d4a2-4448-b33e-8cb8b61369e8)

**Comment by vladplesu** [comment]
I can take this
