### ISSUE TITLE
[NGO Admin] [Forms] The user should not be able to edit& add translations to a published form if the form has answers 

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#525]
The user should not be able to **edit** or **add translations** for a published form if **the form has answers.**
In these cases, when published forms has answers: 
- if the user tries to edit the form with status = published, it should be displayed a message "You can not edit a form that has answers submitted" 
- if the user tries to add translations for a form with status = published, it should be displayed a message "You can not add translations for a form that has answers submitted" 
![Screenshot 2024-05-30 at 16 10 51](https://github.com/commitglobal/votemonitor/assets/137993344/8213a48f-fb73-4408-8fb7-a2c17f08d272)

**Comment by mirunaioana-msc** [comment]
linked to #598
