### ISSUE TITLE
Write Integration Tests for Vote.Monitor.Api.Feature.Observer

### ISSUE THREAD

**Issue by idormenco** [commitglobal/votemonitor#54]
Write integration tests similar to those found in `Vote.Monitor.Api.Feature.PollingStation.IntegrationTests`

**Comment by azooz59T** [comment]
Can I take this, also are there any further instruction on how to spin-up the docker containers ? based on this [PR](https://github.com/commitglobal/votemonitor/pull/70) I can see I will most likely need access to the database to get correct data to test against.

 
![Votemonitor_data](https://github.com/commitglobal/votemonitor/assets/78484811/5dcd45d2-58a7-4347-a017-d22db744feb1)

**Comment by idormenco** [comment]
@azooz59T We use test containers for creating a database for each test.
 If you want to run the API you could use our docker compose file found [here](https://github.com/commitglobal/votemonitor/blob/main/src/Docker-compose/docker-compose.yaml)
 `docker compose up db -d`
