### ISSUE TITLE
[NGO Admin/ Form builder] UI improvements on question card (Iteration 1)

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#601]
Changes ([figma + specifications](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=7025-27435&t=Ly0vjE4EO0Xx30So-4))
- improvements on question ID field (moved at the bottom of the card)
- adding validation rules 
- question text field is mandatory

**Comment by mirunaioana-msc** [comment]
@avasi-code4ro - please test & create new issues if it's the case
