### ISSUE TITLE
[NGO Admin/ Dashboard] implement 2nd row of statistics to be reported for the entire election event (Iteration 1)

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#602]
**UX Solution TBD** @avasi-code4ro 

Current:
For now, the 2nd row of the Dashboard indicators are reported based on the last 12 hours. After the election event is done, the graphs are on the base line (nothing is displayed).

Expected:
For the NGO Admins it would be useful to see the statistics for the entire election event, not just for the last 12 hours, especially after the election event end.

**Comment by mirunaioana-msc** [comment]
create and last updated data is stored and we have to bring them from the DB => redesign needed (cc: @avasi-code4ro )
