### ISSUE TITLE
[NGO Admin/ Dashboard] implement saving form as personal templates/ copy form from one event to another (Iteration 2) 

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#604]
### **User story**
As an NGO admin, I want to save forms as personal templates or to copy forms from one election event to another, so that I can efficiently reuse and manage forms across different election events.

### UX/UI Solution TBD

**Ideas**
- In the observer form list, include an option in the actions menu for each row labeled "Copy form to other event" -> this will open a dialog where the NGO Admin will select the event where the form will be copied to. @avasi-code4ro 
- On the page where the NGO Admin creates a form, in addition to the templates provided by the Super Admin, forms created by the NGO Admin in previous election events should also be available, organized/grouped by the respective election event. -> all these will be displayed in a table list. To see how forms with translations under them will be displayed/ managed. @idormenco

- [ ] To illustrate the ideas in Figma @avasi-code4ro

**Comment by mirunaioana-msc** [comment]
Note:
- creating a form from a template is a nice to have (depends on SuperAdmin implementation which is currently low-priority), while creating a form from a past event has been asked for by the users
