### ISSUE TITLE
Preview Answer on Question Card

### ISSUE THREAD

**Issue by andrei-manda** [commitglobal/votemonitor#614]
## Description

In addition to the current implementation of the question card, the UI has been updated to include previews for answers and media files.

#### Business Rules 

2. Answer previews must be shown based on the question type:
- single-select, number, and date questions: display the selected option or value. 
- multiple-select questions: display selected options, separated by semicolons. 
- text questions: display the first row of text, truncated if is necessary.
3. Attachment icons must represent media files and notes.
- if one or multiple media files are uploaded, show only one media icon.
- for notes, display a truncated preview of the latest note added.

#### Acceptance Criteria

3. For single-select, number, and date questions, the selected option/value is shown as the preview.
4. For multiple-select questions, the selected options are displayed, separated by semicolons.
5. The selected options text for single-select and multiple-select questions will be truncated if necessary.
6. For text-based questions, the first row of text is displayed as a truncated preview if necessary.
7. If one or multiple media files (photo, video or audio) are uploaded, only one media icon is displayed.
8. If multiple notes are added, the system displays a truncated preview of the latest note.

## Figma References [here](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=6548-6432&t=sE1Aw6eQws3j5ZF5-4)

Tasks: 

- [x] 3. For single-select, number, and date questions, the selected option/value is shown as the preview.
- [x] 4. For multiple-select questions, the selected options are displayed, separated by semicolons.
- [x] 5. The selected options text for single-select and multiple-select questions will be truncated if necessary.
- [x] 6. For text-based questions, the first row of text is displayed as a truncated preview if necessary.
- [x] 7. If one or multiple media files (photo, video or audio) are uploaded, only one media icon is displayed.
- [x] 8. If multiple notes are added, the system displays a truncated preview of the latest note.
- [ ] Testing done

**Comment by MarG66** [comment]
@andrei-manda Passed Testing, ready for deploy.
