### ISSUE TITLE
Bulk Changes on Inbox Page

### ISSUE THREAD

**Issue by andrei-manda** [commitglobal/votemonitor#618]
## Description

1. Implement a feature on the message cards page that detects links and phone numbers: 
- when a user clicks on a link, they should be redirected to the appropriate URL. 
- if a phone number is clicked, it should open the phone app with the number pre-filled for calling.

2. The message cards should disable tap feedback.

3. The user should be able to copy the card text to the clipboard.

**Comment by luciatugui** [comment]
The 3rd point "The user should be able to copy the card text to the clipboard" was discussed with Avasi and decided to no longer implement, as we already have all of the other features that open email, dial, external links.
