### ISSUE TITLE
Remove Kebab Menu on All Pages Except Observation

### ISSUE THREAD

**Issue by andrei-manda** [commitglobal/votemonitor#628]
## As is

The kebab menu with the 'Manage My Polling Station' option is visible on every page accessed via the bottom navigation menu.

## Should be

- [x] The kebab menu should be displayed only on the Observation page.

**Comment by luciatugui** [comment]
Will be ready for testing on next staging deploy.

**Comment by MarG66** [comment]
@andrei-manda Passed testing, ready for deploy.
