### ISSUE TITLE
Manually Mark Forms and PSI Forms as Completed

### ISSUE THREAD

**Issue by andrei-manda** [commitglobal/votemonitor#632]
## [PENDING] - SOLUTION TO BE DEFINED 

De la Avasi: ```Mark form as done - am discutat si vom ramane la solutia initiala, deoarece nu dorim sa mai adaugam complexitate pe fiecare intrebare si marcarea unui form overall ca done a reiesit si din feedback. [Aici](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=6891-5698&t=KnYmRxHVcCTQLTFJ-4) am refacut flow-urile si pus notite. Puteti sa mai aruncati un ochi peste si discutam luni daca mai gasim edge case-uri ciudatele.```

**Comment by avasi-code4ro** [comment]
Figma [here](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=6891-5698&t=5u5sefHBtot6H7pz-4)

**Comment by radulescuandrew** [comment]
@Mario Grigorosita @Andrei Manda


1. Polling station information form 
- Se poate pune in done/in-progress >>>>oricand<<<<, chiar daca nu ai completat nicio intrebare
- Se foloseste acelasi endpoint ca pentru arrival/departure time/answers/breaks cu un field nou isCompleted: boolean
- Functioneaza offline, la fel ca orice actiune
- Daca faci Mark as done si dai Reset form , iti ramane Mark as done pe care il poti trece in In-progress daca vrei si inapoi in Mark-as-Done (vezi punct a)
2. Form 
- Poti face Mark as done >>>>doar daca ai cel putin o intrebare<<<< la care ai raspuns
- Este un endpoint separat /form-submissions/:setCompletioncare va shareui acelasi scopeId cu POST form-submissions ca sa putem trimite requesturile offline consecutiv ci nu in paralel (nu merge sa faci Mark as done daca nu ai submissionId)
- Functioneaza offline, la fel ca orice actiune


Shared logic:
- Nu poti face Mark as done daca toate intrebarile sunt raspunse (answers.length === questions.length) => Este disabled butonul
- De aici trebuie extrapolat un TestCase sa verificam intrebarile cu jump-logic si ca logica sta in picioare :standing_person::skin-tone-2: 
- Poti face Mark as in-progress daca toate intrebarile sunt raspunse => statusul afisat va fi din Mark as done in Done
- Daca faci Mark as done si dai Reset form , iti ramane Mark as done pe care il poti trece in In-progress.apoi daca vrei sa-l treci in Mark as done vezi punct a
