### ISSUE TITLE
Notification Systems (New Guides/New Message-Badges)

### ISSUE THREAD

**Issue by andrei-manda** [commitglobal/votemonitor#633]

**Comment by mirunaioana-msc** [comment]
Does this need to be moved to the milestone related to Mobile issues?

**Comment by avasi-code4ro** [comment]
Reference discussion [here](https://codeforromania.slack.com/archives/C06LDT1JMFA/p1725275949999709) 
Figma: [here](https://www.figma.com/design/OdPI6l30uEbnYfxMpoulhD/Vote-Monitor-2.0?node-id=7893-7014&t=VVtrXT3BQdH4iVv2-4)

Options:
- badge in navigation on the inbox section where we count new unopened messages + badge on the app (before you open it) - desired option
- only red dot without counter on navigation - if the first option is not possible
