### ISSUE TITLE
[NGO Admin] [Observer Guides] Upload accepts only .csv files

### ISSUE THREAD

**Issue by mirunaioana-msc** [commitglobal/votemonitor#649]
Steps to Reproduce:

1. Go to "Election event"
2. Select "Observer Guides" tab
3. Click "Upload observer guide"
4. Try to upload a .pdf file
5. See error (all the files excepting the .csv ones are disabled)

This could be linked to the validation made for uploading observers.

**Comment by idormenco** [comment]
fixed in #651
