### ISSUE TITLE
Rich text editor

### ISSUE THREAD

**Issue by idormenco** [commitglobal/votemonitor#708]
- [ ]  add rich text editor similar to [this](https://shadcn-minimal-tiptap.vercel.app/) 
- [ ]  remove image upload
- [ ]  rich text editor should produce HTML
- [ ]  3 type of links should be supported url/ tel / mailto
- [ ]  use this in notifications sending and guides
- [ ] remove preview of the text notification from tables
- [ ] use html preview in view mode of notifications / guides

**Comment by imdeaconu** [comment]
Can I be assigned to this, please? Thanks!
