### ISSUE TITLE
[NGO Admin] Inconsistent font size for the title and subtitle across pages & misalignment in the subtitle box

### ISSUE THREAD

**Issue by avasi-code4ro** [commitglobal/votemonitor#733]
The font size used for the main title and the subtitle inside the box varies across different pages. Some pages have larger font sizes, while others are smaller, leading to an inconsistent design. Additionally, the subtitle inside the box is not always left-aligned with the underline below.

### **Expected Behavior**
- The font size for the title and the subtitle inside the box should be the same on all pages.
- The subtitle inside the box should be left-aligned with the underline, as shown in the screenshot below
<img width="921" alt="Screenshot 2024-10-09 at 11 24 47" src="https://github.com/user-attachments/assets/38d3878e-20bc-4a51-98ad-ab383f8ce46e">

### **Pages that need to be investigated and updated accordingly**:
- All pages that have tabs: Election event, Observers, Individual observer view, Responses

**Comment by swarupn17** [comment]
Hello @mirunaioana-msc  @avasi-code4ro I can do this task. I have good prior experience in designing webpages. Please can you assign this task to me.
Thanks !

**Comment by idormenco** [comment]
@swarupn17 Hi, 
thanks for your interest in helping us with this issue.
You can start working on it.
To have access to some testing data connect to staging env:

1. copy `.env.example` as `.env`
2. change it's content to `VITE_API_URL=https://votemonitor.staging.heroesof.tech/api/`
3. use  this credentials:
-  "email": "sebastian@example.com", 
- "password": "string"
